# Generated by Django 3.0.7 on 2020-06-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200626_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slung',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slung',
            new_name='slug',
        ),
    ]
